### ISSUE TITLE
next milestone planning

### ISSUE THREAD

**Issue by Jcroxford** [UVU-Open-Source/wagstaff-grader-aide#7]
### Views
- list of active courses where you are a teacher
- list of assignments for a course
- list of students in a course possibly including their id's for canvas, zybooks, and uvu

### Types of assignments
zybooks chapters
zybooks auto coding thing
physical assignments (quizzes, discrete math hw, tests)
canvas submitted assignment with files/zip
canvas submitted assignment with text only

**Comment by Jcroxford** [comment]
### Things that need doing

**spa**
- [ ] course views needs planned and built
- [ ] assignment views needs planned and built
- [ ] route guards for invalid auth need to be made and used

**server**
